version: '3.12'

services:
  web:
    image: fyle-interview-intern-backend:latest
    ports:
      - "9999:9999"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - GUNICORN_PORT=9999
    command: ["gunicorn", "-c", "gunicorn_config.py", "core.server:app"]